/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Controller.GestoreFile;
import Controller.GestoreGenerale;
import model.Appello;

/**
 *
 * @author leporatil
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DocentiBt = new javax.swing.JButton();
        StudentiBt = new javax.swing.JButton();
        CorsiBt = new javax.swing.JButton();
        AppelliBt = new javax.swing.JButton();
        IscrizioniBt = new javax.swing.JButton();
        DisciplineBt = new javax.swing.JButton();
        title = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        DocentiBt.setText("Docenti");
        DocentiBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DocentiBtActionPerformed(evt);
            }
        });

        StudentiBt.setText("Studenti");
        StudentiBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentiBtActionPerformed(evt);
            }
        });

        CorsiBt.setText("Corsi");
        CorsiBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CorsiBtActionPerformed(evt);
            }
        });

        AppelliBt.setText("Appelli");
        AppelliBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AppelliBtActionPerformed(evt);
            }
        });

        IscrizioniBt.setText("Iscrizioni");
        IscrizioniBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IscrizioniBtActionPerformed(evt);
            }
        });

        DisciplineBt.setText("Discipline");
        DisciplineBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisciplineBtActionPerformed(evt);
            }
        });

        title.setText("Gestione Università");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(DisciplineBt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(IscrizioniBt)
                .addGap(66, 66, 66))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(DocentiBt)
                        .addGap(55, 55, 55)
                        .addComponent(StudentiBt))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(CorsiBt)
                        .addGap(69, 69, 69)
                        .addComponent(AppelliBt))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(title)))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(title)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DocentiBt)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(StudentiBt)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(CorsiBt))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(AppelliBt)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(IscrizioniBt)
                        .addGap(75, 75, 75))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(DisciplineBt)
                        .addGap(56, 56, 56))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DocentiBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DocentiBtActionPerformed
        // TODO add your handling code here:
        DocentiDialog dd = new DocentiDialog(this, true);
        dd.setVisible(true);
        
        
    }//GEN-LAST:event_DocentiBtActionPerformed

    private void StudentiBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentiBtActionPerformed
        StudentiDialog sd = new StudentiDialog(this, true);
        sd.setVisible(true);
    }//GEN-LAST:event_StudentiBtActionPerformed

    private void CorsiBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CorsiBtActionPerformed
        CorsiDialog cd = new CorsiDialog(this, true);
        cd.setVisible(true);
    }//GEN-LAST:event_CorsiBtActionPerformed

    private void AppelliBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AppelliBtActionPerformed
        AppelliDialog ad = new AppelliDialog(this, true);
        ad.setVisible(true);
    }//GEN-LAST:event_AppelliBtActionPerformed

    private void IscrizioniBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IscrizioniBtActionPerformed
        IscrizioniDialog id = new IscrizioniDialog(this, true);
        id.setVisible(true);
    }//GEN-LAST:event_IscrizioniBtActionPerformed

    private void DisciplineBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisciplineBtActionPerformed
        DisciplineDialog did = new DisciplineDialog(this, true);
        did.setVisible(true);
    }//GEN-LAST:event_DisciplineBtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                
                //aaaaaa
                
                GestoreGenerale gg = GestoreGenerale.getInstance();
                
               
                GestoreFile.scriviAppelli(gg.gestAppelli);
                    
                
               
                new Home().setVisible(true);
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AppelliBt;
    private javax.swing.JButton CorsiBt;
    private javax.swing.JButton DisciplineBt;
    private javax.swing.JButton DocentiBt;
    private javax.swing.JButton IscrizioniBt;
    private javax.swing.JButton StudentiBt;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}


